version: '3.5'

services:
  spawn:
    image: itzg/minecraft-server
    ports:
      - 25571:25565
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      ONLINE_MODE: "FALSE"
      MEMORY: "2G"
      VERSION: "1.19.2"
      MOTD: "Reost Spawn"
      MAX_PLAYERS: "64"
      LEVEL_NAME: "InselDerZeiten"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /home/docker-minecraft/spawn:/data
  reost:
    image: itzg/minecraft-server
    ports:
      - 25572:25565
      - 8123:8123
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      ONLINE_MODE: "FALSE"
      MEMORY: "8G"
      VERSION: "1.19.2"
      MOTD: "Reost"
      MAX_PLAYERS: "1024"
      LEVEL_NAME: "Reost"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /home/docker-minecraft/reost:/data
  proxy:
    image: itzg/bungeecord
    environment:
      BUNGEE_JAR_REVISION: "1"
      CFG_MOTD: "Reost"
      REPLACE_ENV_VARIABLES: "true"
      TYPE: "WATERFALL"
      MEMORY: "4G"
      MOTD: "Reost"
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - 25565:25565
      - 8800:8800
    volumes:
      - /home/docker-minecraft/proxy/_config:/config
      - /home/docker-minecraft/proxy/_plugins:/plugins
      - /home/docker-minecraft/proxy:/server
